Feat: WolfNormalSkill#32
AOW-GroupProject/AgeOfWolves pull request #40
Opened 2024-06-20 12:01 UTC by chahg0514

## #️⃣연관된 이슈

> resolves #32, ref -, related to - 

## 📝작업 내용

> 1. 늑대 이동 스킬 함수 제작
> 2. 데이터 구조체 작성
> 3. sight config 사용
> 4. 부드러운 rotation(Patrol 점에서 점으로)

## ⚡️스크린 샷

2024-06-24 10:28 UTC, Seo-BJ approved these changes

2024-06-24 15:18 UTC, Yongsullee requested changes
고생하셨습니다!

리뷰 내용 한번 읽어 보시고, 답변 주시면 Approve 진행하겠습니다!

2024-06-24 15:18 UTC, Yongsullee commented on Source/AgeOfWolves/10_Monster/CustomEnum.cpp
> +	PrimaryActorTick.bCanEverTick = true;
단순히 AI 관련 Enum 들을 정의하기 위해 활용하는 클래스라면, PrimaryActorTick을 false로 설정하는게 좋을 것 같습니다.

이와 관련해, Tick 함수도 지워주는게 성능 향상에 도움이 될 것 같습니다. 

Custom Enum 객체를 Game World에 Spawn할 일이 없기 때문에, 사실 크게 상관은 없지만, 이후 개발 과정에서 ACustomEnum 클래스의 목적에 대하여 헷갈릴 수 있기 때문에 생성자 정도만 남겨두고 다 지워도 괜찮을 것 같습니다.

2024-06-24 15:18 UTC, Yongsullee commented on Source/AgeOfWolves/10_Monster/MonsterData.h
> +struct FSkillData
혹시 FSkillData 보다, FEnemySkillData 혹은 FMonsterSkillData로 변경하는게 어떨까요?

Character의 것인지, Enemy의 것인지 헷갈릴 수 있기 때문입니다!

2024-06-24 15:18 UTC, Yongsullee commented on Source/AgeOfWolves/10_Monster/MonsterData.h
> +struct FPermanentStat : public FTableRowBase
BaseAttributeSet에 Health 수치 값 혹은 별도의 추가적인 Attribute를 설정 가능하지만, 별도로 PDamageStat과 PHealthStat을 별도의 구조체에 넣은 이유가 궁금합니다!

2024-06-25 06:56 UTC, chahg0514 commented on Source/AgeOfWolves/10_Monster/MonsterData.h
> +	NormalA UMETA(DisplayName = "normalA"),
기획에 있는대로 구분했습니다. NormalA가 원거리입니다.

2024-06-25 06:59 UTC, chahg0514 commented on Source/AgeOfWolves/10_Monster/MonsterData.h
> +struct FPermanentStat : public FTableRowBase
몬스터 타입마다 고정 스탯이 있는 방식입니다. 그냥 SingleMonsterData에 합치는게 좋을 것 같아서 저도 기획자분한테 혹시 나중에 고정 스탯이 추가될 예정인지 여쭤본 상태입니다.

2024-06-25 06:59 UTC, chahg0514 commented on Source/AgeOfWolves/10_Monster/MonsterData.h
> +struct FSkillData
넵 변경하겠습니다.

2024-06-26 12:08 UTC, Yongsullee approved these changes
고생하셨습니다

2024-06-26 12:09 UTC, merged